{
 "title": "fastq-exporter",
 "tags": [ "mONiTor" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "address",
    "label": "address",
    "query": {
     "query": "label_values(fastq_total_size,address)"
    }
   },
   {
    "name": "path",
    "label": "path",
    "query": {
     "query": "label_values(fastq_total_size{address=\"$address\"},path)"
    }
   },
   {
    "name": "channel",
    "label": "channel",
    "query": {
     "query": "label_values(fastq_amount_reads{address=\"$address\", path=\"$path\"},channel)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total number of reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sum(fastq_amount_reads)", "legendFormat": "total number of reads" }
   ]
  },
  {
   "title": "Total number of bases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(fastq_amount_A)+sum(fastq_amount_C)+sum(fastq_amount_G)+sum(fastq_amount_T)+sum(fastq_amount_N)",
     "legendFormat": "total number of bases"
    }
   ]
  },
  {
   "title": "Longest read length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "max(fastq_max_read)", "legendFormat": "longest read length" }
   ]
  },
  {
   "title": "Average read length ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "(sum(fastq_amount_A)+sum(fastq_amount_C)+sum(fastq_amount_G)+sum(fastq_amount_T)+sum(fastq_amount_N))/sum(fastq_amount_reads)",
     "legendFormat": "average read length"
    }
   ]
  },
  {
   "title": "Total number of nucleotides",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(fastq_amount_A)/(sum(fastq_amount_A)+sum(fastq_amount_C)+sum(fastq_amount_G)+sum(fastq_amount_T)+sum(fastq_amount_N))",
     "legendFormat": "A"
    },
    {
     "expr": "sum(fastq_amount_C)/(sum(fastq_amount_A)+sum(fastq_amount_C)+sum(fastq_amount_G)+sum(fastq_amount_T)+sum(fastq_amount_N))",
     "legendFormat": "C"
    },
    {
     "expr": "sum(fastq_amount_G)/(sum(fastq_amount_A)+sum(fastq_amount_C)+sum(fastq_amount_G)+sum(fastq_amount_T)+sum(fastq_amount_N))",
     "legendFormat": "G"
    },
    {
     "expr": "sum(fastq_amount_T)/(sum(fastq_amount_A)+sum(fastq_amount_C)+sum(fastq_amount_G)+sum(fastq_amount_T)+sum(fastq_amount_N))",
     "legendFormat": "T"
    },
    {
     "expr": "sum(fastq_amount_N)/(sum(fastq_amount_A)+sum(fastq_amount_C)+sum(fastq_amount_G)+sum(fastq_amount_T)+sum(fastq_amount_N))",
     "legendFormat": "N"
    }
   ]
  },
  {
   "title": "Total average quality",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    { "expr": "fastq_total_average_quality", "legendFormat": "total average quality" }
   ]
  },
  { "title": "Per channel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Number of reads per channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "fastq_amount_reads{channel=\"$channel\"}",
     "legendFormat": "number of reads per channel"
    }
   ]
  },
  {
   "title": "Number of bases per channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum(fastq_amount_A{channel=\"$channel\"})+sum(fastq_amount_C{channel=\"$channel\"})+sum(fastq_amount_G{channel=\"$channel\"})+sum(fastq_amount_T{channel=\"$channel\"})+sum(fastq_amount_N{channel=\"$channel\"})",
     "legendFormat": "number of bases per channel"
    }
   ]
  },
  {
   "title": "Longest read length per channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "fastq_max_read{channel=\"$channel\"}",
     "legendFormat": "longest read length per channel"
    }
   ]
  },
  {
   "title": "Average read length per channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "(sum(fastq_amount_A{channel=\"$channel\"})+sum(fastq_amount_C{channel=\"$channel\"})+sum(fastq_amount_G{channel=\"$channel\"})+sum(fastq_amount_T{channel=\"$channel\"})+sum(fastq_amount_N{channel=\"$channel\"})) / sum(fastq_amount_reads{channel=\"$channel\"})",
     "legendFormat": "average read length per channel"
    }
   ]
  },
  {
   "title": "Number of nucleotides per channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "sum(fastq_amount_A{channel=\"$channel\"})/(sum(fastq_amount_A{channel=\"$channel\"})+sum(fastq_amount_C{channel=\"$channel\"})+sum(fastq_amount_G{channel=\"$channel\"})+sum(fastq_amount_T{channel=\"$channel\"})+sum(fastq_amount_N{channel=\"$channel\"}))",
     "legendFormat": "A"
    },
    {
     "expr": "sum(fastq_amount_C{channel=\"$channel\"})/(sum(fastq_amount_A{channel=\"$channel\"})+sum(fastq_amount_C{channel=\"$channel\"})+sum(fastq_amount_G{channel=\"$channel\"})+sum(fastq_amount_T{channel=\"$channel\"})+sum(fastq_amount_N{channel=\"$channel\"}))",
     "legendFormat": "C"
    },
    {
     "expr": "sum(fastq_amount_G{channel=\"$channel\"})/(sum(fastq_amount_A{channel=\"$channel\"})+sum(fastq_amount_C{channel=\"$channel\"})+sum(fastq_amount_G{channel=\"$channel\"})+sum(fastq_amount_T{channel=\"$channel\"})+sum(fastq_amount_N{channel=\"$channel\"}))",
     "legendFormat": "G"
    },
    {
     "expr": "sum(fastq_amount_T{channel=\"$channel\"})/(sum(fastq_amount_A{channel=\"$channel\"})+sum(fastq_amount_C{channel=\"$channel\"})+sum(fastq_amount_G{channel=\"$channel\"})+sum(fastq_amount_T{channel=\"$channel\"})+sum(fastq_amount_N{channel=\"$channel\"}))",
     "legendFormat": "T"
    },
    {
     "expr": "sum(fastq_amount_N{channel=\"$channel\"})/(sum(fastq_amount_A{channel=\"$channel\"})+sum(fastq_amount_C{channel=\"$channel\"})+sum(fastq_amount_G{channel=\"$channel\"})+sum(fastq_amount_T{channel=\"$channel\"})+sum(fastq_amount_N{channel=\"$channel\"}))",
     "legendFormat": "N"
    }
   ]
  },
  {
   "title": "Average quality per channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "fastq_average_quality{channel=\"$channel\"}",
     "legendFormat": "average quality per channel"
    }
   ]
  }
 ]
}