{
 "title": "fast5-exporter",
 "tags": [ "mONiTor" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "address",
    "label": "address",
    "query": {
     "query": "label_values(fast5_amount_reads,address)"
    }
   },
   {
    "name": "path",
    "label": "path",
    "query": {
     "query": "label_values(fast5_amount_reads{address=\"$address\"},path)"
    }
   },
   {
    "name": "channel",
    "label": "channel",
    "query": {
     "query": "label_values(fast5_raw_data_length{address=\"$address\", path=\"$path\"},channel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  {
   "title": "Total raw data length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "sum(fast5_raw_data_length)", "legendFormat": "total raw data length" }
   ]
  },
  {
   "title": "Total number of reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    { "expr": "sum(fast5_amount_reads)", "legendFormat": "total number of reads" }
   ]
  },
  {
   "title": "Average raw data length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(fast5_raw_data_length) / sum(fast5_amount_reads)",
     "legendFormat": "average raw data length"
    }
   ]
  },
  {
   "title": "Max raw data length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "max(fast5_max_raw_data_length)", "legendFormat": "max raw data length" }
   ]
  },
  { "title": "Per channel", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Raw data length per channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "fast5_raw_data_length{channel=\"$channel\"}",
     "legendFormat": "raw data length per channel"
    }
   ]
  },
  {
   "title": "Number of reads per channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "fast5_amount_reads{channel=\"$channel\"}",
     "legendFormat": "number of reads per channel"
    }
   ]
  },
  {
   "title": "Average raw data length per channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(fast5_raw_data_length{channel=\"$channel\"}) / sum(fast5_amount_reads{channel=\"$channel\"})",
     "legendFormat": "average raw data length per channel"
    }
   ]
  },
  {
   "title": "Max raw data length per channel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "fast5_max_raw_data_length{channel=\"$channel\"}",
     "legendFormat": "max raw data length per channel"
    }
   ]
  }
 ]
}