{
 "title": "minknow-exporter",
 "tags": [ "mONiTor" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "address",
    "label": "address",
    "query": {
     "query": "label_values(minknow_flowcell_info,address)"
    }
   },
   {
    "name": "deviceId",
    "label": "deviceId",
    "query": {
     "query": "label_values(minknow_flowcell_info{address=\"$address\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "MinKNOW", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Pore states",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minknow_pending_mux_change{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "pending_mux_change"
    },
    {
     "expr": "minknow_unavailable{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "unavailable"
    },
    {
     "expr": "minknow_inrange{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "inrange"
    },
    {
     "expr": "minknow_above{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "above"
    },
    {
     "expr": "minknow_strand{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "strand"
    },
    {
     "expr": "minknow_below{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "below"
    },
    {
     "expr": "minknow_multiple{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "multiple"
    },
    {
     "expr": "minknow_saturated{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "saturated"
    },
    {
     "expr": "minknow_good_single{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "good_single"
    },
    {
     "expr": "minknow_unknown{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "unknown"
    },
    {
     "expr": "minknow_unclassified{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "unclassified"
    },
    {
     "expr": "minknow_unblocking{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "unblocking"
    },
    {
     "expr": "minknow_adapter{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "adapter"
    }
   ]
  },
  {
   "title": "Pore states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "minknow_pending_mux_change{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "pending_mux_change"
    },
    {
     "expr": "minknow_unavailable{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "unavailable"
    },
    {
     "expr": "minknow_inrange{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "inrange"
    },
    {
     "expr": "minknow_above{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "above"
    },
    {
     "expr": "minknow_strand{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "strand"
    },
    {
     "expr": "minknow_below{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "below"
    },
    {
     "expr": "minknow_multiple{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "multiple"
    },
    {
     "expr": "minknow_saturated{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "saturated"
    },
    {
     "expr": "minknow_good_single{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "good_single"
    },
    {
     "expr": "minknow_unknown{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "unknown"
    },
    {
     "expr": "minknow_unclassified{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "unclassified"
    },
    {
     "expr": "minknow_unblocking{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "unblocking"
    },
    {
     "expr": "minknow_adapter{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "adapter"
    }
   ]
  },
  {
   "title": "Estimated selected bases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "minknow_estimated_selected_bases{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "estimated_selected_bases"
    }
   ]
  },
  {
   "title": "Read count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(minknow_read_count{address=\"$address\", name=\"$deviceId\"})",
     "legendFormat": "read_count"
    }
   ]
  },
  {
   "title": "Basecalled bases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "minknow_basecalled_fail_bases{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "fail_bases"
    },
    {
     "expr": "minknow_basecalled_pass_bases{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "pass_bases"
    }
   ]
  },
  {
   "title": "Basecalled read count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "minknow_basecalled_fail_read_count{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "fail_read_count"
    },
    {
     "expr": "minknow_basecalled_pass_read_count{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "pass_read_count"
    },
    {
     "expr": "minknow_basecalled_skipped_read_count{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "skipped_read_count"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "minknow_asic_temp{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "asic_temp"
    },
    {
     "expr": "minknow_heat_sink_temp{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "heat_sink_temp"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "minknow_bias_voltage{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "bias_voltage"
    }
   ]
  },
  {
   "title": "Alignment",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "sum(minknow_alignment_deletions{address=\"$address\", name=\"$deviceId\"})",
     "legendFormat": "deletions"
    },
    {
     "expr": "sum(minknow_alignment_insertions{address=\"$address\", name=\"$deviceId\"})",
     "legendFormat": "insertions"
    },
    {
     "expr": "sum(minknow_alignment_matches{address=\"$address\", name=\"$deviceId\"})",
     "legendFormat": "matches"
    },
    {
     "expr": "sum(minknow_alignment_mismatches{address=\"$address\", name=\"$deviceId\"})",
     "legendFormat": "mismatches"
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "minknow_alignment_coverage{address=\"$address\", name=\"$deviceId\"}",
     "legendFormat": "coverage"
    }
   ]
  }
 ]
}