{
 "title": "master",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "address",
    "label": "address",
    "query": {
     "query": "label_values(minknow_flowcell_info,address)"
    }
   },
   {
    "name": "flowcell",
    "label": "flowcell",
    "query": {
     "query": "label_values(minknow_flowcell_info,name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "MinKNOW",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flow cell state",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "count by(state) (minknow_flowcell_info{address=\"$address\", name=\"$flowcell\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Read count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum(minknow_read_count{address=\"$address\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "minknow_fraction_basecalled{address=\"$address\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "minknow_fraction_skipped{address=\"$address\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Basecalled bases",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "minknow_basecalled_fail_bases{address=\"$address\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "minknow_basecalled_pass_bases{address=\"$address\"}",
       "legendFormat": "__auto"
      },
      {}
     ]
    },
    {
     "title": "Alignment",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "sum(minknow_alignment_coverage{address=\"$address\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(minknow_alignment_deletions{address=\"$address\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(minknow_alignment_insertions{address=\"$address\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(minknow_alignment_matches{address=\"$address\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(minknow_alignment_mismatches{address=\"$address\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Basecalled read count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "minknow_basecalled_fail_read_count{address=\"$address\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "minknow_basecalled_pass_read_count{address=\"$address\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "minknow_basecalled_skipped_read_count{address=\"$address\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "FASTQ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true
  },
  { "title": "FAST5", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Number of FAST5 files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kafka_topic_partition_oldest_offset)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}